DEMOCORE/Models/Admin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DEMOCORE.Models
{
    public class Admin
    {
        public int ID { get; set; }
    }
}

DEMOCORE/Models/Book.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DEMOCORE.Models
{
    public class Book
    {
        public int ID { get; set; }

        [StringLength(100, MinimumLength = 5)]
        [Required(ErrorMessage = "Please enter the title of your book")]
        public string Title { get; set; }
       
        [Required(ErrorMessage = "Please enter the author name")]
        public string Author { get; set; }

        [StringLength(500)]
        public string Des { get; set; }
        public string Category { get; set; }

        [Required(ErrorMessage = "Please enter the total pages")]
        [Display(Name = "Total pages of book")]
        public int Totalpages { get; set; }
        public string Language { get; set; }
       
        [Display(Name = "Choose the cover photo of your book")]
        [Required]
        public IFormFile CoverPhoto { get; set; }
        public string CoverImageUrl { get; set; }
    }
}

DEMOCORE/Models/ErrorViewModel.cs
using System;

namespace DEMOCORE.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DEMOCORE/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DEMOCORE.Models;

namespace DEMOCORE.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public ViewResult Index()
        {
            return View();
        }

        public IActionResult Indexx()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            int i = 0;
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DEMOCORE/Controllers/booksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DEMOCORE.Data;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using DEMOCORE.Repository;
using DEMOCORE.Models;
using Microsoft.AspNetCore.Http;

namespace DEMOCORE.Controllers
{
    public class booksController : Controller
    {
        private readonly BookStoreContext _context;
        private readonly IBookRepository _bookRepository = null;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public booksController(BookStoreContext context, IWebHostEnvironment webHostEnvironment, IBookRepository bookRepository)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _bookRepository = bookRepository; 
        }

        // GET: books
        public async Task<ViewResult> Index()
        {
            return View(await _bookRepository.GetAllBooks());
        }

        // GET: books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var books = await _context.books
                .FirstOrDefaultAsync(m => m.ID == id);
            if (books == null)
            {
                return NotFound();
            }

            return View(books);
        }

        // GET: books/Create
        public IActionResult Create(bool isSuccess = false, int bookId = 0)
        {
            ViewBag.IsSuccess = isSuccess;
            ViewBag.BookId = bookId;
            return View();
        }

        // POST: books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Book books)
        {
            if (ModelState.IsValid)
            {
                if (books.CoverPhoto != null)
                {
                    string folder = "books/cover/";
                    books.CoverImageUrl = await UploadImage(folder, books.CoverPhoto);
                }
                int id = await _bookRepository.AddNewBook(books);
                if (id > 0)
                {
                    return RedirectToAction(nameof(Create), new { isSuccess = true, bookId = id });
                }
            }
            return View(books);
        }

        // GET: books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var books = await _context.books.FindAsync(id);
            if (books == null)
            {
                return NotFound();
            }
            return View(books);
        }

        // POST: books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,Author,Des,Category,Totalpages,Language")] books books)
        {
            if (id != books.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    _context.Update(books);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!booksExists(books.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(books);
        }

        // GET: books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var books = await _context.books
                .FirstOrDefaultAsync(m => m.ID == id);
            if (books == null)
            {
                return NotFound();
            }

            return View(books);
        }

        // POST: books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var books = await _context.books.FindAsync(id);
            _context.books.Remove(books);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool booksExists(int id)
        {
            return _context.books.Any(e => e.ID == id);
        }

        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {

            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;

            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);

            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

            return "/" + folderPath;
        }
    }
}

DEMOCORE/Views/Home/Index.cshtml
@{
    
    ViewData["Title"] = "Home Page";
}

<section class="jumbotron text-center">
    <div class="container">
        <h1>Welcome To BookStore</h1>
        <p class="lead text-muted">
        Buyi ng the necessary things from a grocery store is called grocery shopping. Now a days, grocery stores are available at everywhere. All kinds of daily necessary things like milk, eggs, bread, oil, sugar, salt, cool-drinks etc are found , Codder
        </p>
        <p>
            <a href="#" class="btn btn-primary my-2">Search Books</a>
        </p> 
    </div>
</section>

DEMOCORE/Views/books/Create.cshtml
@model DEMOCORE.Models.Book

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!--This is breadcrumbs items -->
<nav aria-label="breadcrumb">
    <nav class="breadcrumbs">
        <a asp-controller="home" asp-action="index" class="breadcrumbs__item">Home</a>
        <a asp-controller="books" asp-action="index" class="breadcrumbs__item">List Book</a>
        <a asp-controller="books" asp-action="Create" class="breadcrumbs__item">Add Book</a>
    </nav>
</nav>
<hr />


<!--This is alert message -->
@if (ViewBag.IsSuccess == true)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Congratulations</strong> You have added new book successfully.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}



<!--This is Spinners-->
<div class="d-flex justify-content-center">
    <div class="spinner-border" role="status" id="myloader" style="display:none">
        <span class="sr-only">Loading...</span>
    </div>
</div>

<!--This is Forms-->
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Book Table</h4>
            <p class="card-description"> Basic Book Information </p>
            <form method="post" enctype="multipart/form-data" class="forms-sample" asp-action="Create">

                @*data-ajax="true" data-ajax-loading="#myloader"*@

                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-row">
                    <div class="col-md-4 mb-3">
                        <label asp-for="Title"></label>
                        <input asp-for="Title" class="form-control" placeholder="Title Book" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                        <div class="valid-tooltip">
                            Looks good!
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <label asp-for="Author" for="validationTooltip02"></label>
                        <input asp-for="Author" class="form-control" id="validationTooltip02" placeholder="Author Book" />
                        <span asp-validation-for="Author" class="text-danger"></span>
                        <div class="valid-tooltip">
                            Looks good!
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <label asp-for="Totalpages" class="control-label" for="validationTooltip03"></label>
                        <input asp-for="Totalpages" type="number" class="form-control" id="validationTooltip03" placeholder="Total pages">
                        <span asp-validation-for="Totalpages" class="text-danger"></span>
                        <div class="invalid-tooltip">
                            Please provide a valid city.
                        </div>
                    </div>

                </div>

                <div class="form-row">
                    <div class="col-md-4 mb-3">
                        <label asp-for="Category" class="control-label" for="validationTooltip04"></label>
                        <input asp-for="Category" class="form-control" id="validationTooltip04" placeholder="Category">
                        <span asp-validation-for="Category" class="text-danger"></span>
                        <div class="invalid-tooltip">
                            Please provide a valid Category.
                        </div>
                    </div>
                    <div class="col-md-8 mb-3">
                        <label asp-for="Language" class="control-label" for="validationTooltip05"></label>
                        <select asp-for="Language" class="form-control" id="validationTooltip04" placeholder="Language" required>
                            <option value="">--Chose Language--</option>
                            <option>English</option>
                            <option>China</option>
                            <option>Dutch</option>
                            <option>Arabic</option>
                        </select>
                        <div class="invalid-tooltip">
                            Please provide a valid zip.
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col-md-12 mb-3">
                        <div class="form-group green-border-focus">
                            <label asp-for="CoverPhoto" class="control-label"></label>
                            <div class="custom-file">
                                <input asp-for="CoverPhoto" class="custom-file-input" id="customFile">
                                <label class="custom-file-label" for="customFile">Choose file</label>
                            </div>
                            <span asp-validation-for="CoverPhoto" class="text-danger"></span>
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col-md-12 mb-3">
                        <div class="form-group green-border-focus">
                            <label asp-for="Des" class="control-label" for="exampleFormControlTextarea5">Description</label>
                            <textarea asp-for="Des" class="form-control" placeholder="Description Here !" id="exampleFormControlTextarea5" rows="3"></textarea>
                        </div>

                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-action="Index" class="btn btn-outline-dark">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>

DEMOCORE/Views/books/Delete.cshtml
@model DEMOCORE.Data.books

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>books</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Des)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Des)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Totalpages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Totalpages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Language)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Language)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DEMOCORE/Views/books/Details.cshtml
@model DEMOCORE.Data.books

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>books</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Des)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Des)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Totalpages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Totalpages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Language)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Language)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DEMOCORE/Views/books/Edit.cshtml
@model DEMOCORE.Data.books

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>books</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Des" class="control-label"></label>
                <input asp-for="Des" class="form-control" />
                <span asp-validation-for="Des" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Totalpages" class="control-label"></label>
                <input asp-for="Totalpages" class="form-control" />
                <span asp-validation-for="Totalpages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Language" class="control-label"></label>
                <input asp-for="Language" class="form-control" />
                <span asp-validation-for="Language" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DEMOCORE/Views/books/Index.cshtml
@model IEnumerable<DEMOCORE.Models.Book>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<nav aria-label="breadcrumb">
    <nav class="breadcrumbs">
        <a asp-controller="home" asp-action="index" class="breadcrumbs__item">Home</a>
        <a asp-controller="books" asp-action="index" class="breadcrumbs__item">List Book</a>
    </nav>
</nav>
<hr />

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>


    
        <table id="example" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>

                    <th>
                        Title
                    </th>
                    <th>
                        Author Name
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        Total pages
                    </th>
                    <th>
                        Language
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>


                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Author)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Des)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Totalpages)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Language)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID" class="btn btn-sm bg-success-light">
                            <i class="fas fa-edit"></i> تعديل
                        </a>
                        <a asp-action="Details" asp-route-id="@item.ID" class="btn btn-sm bg-info-light">
                            <i class="far fa-eye"></i> عرض التفاصيل
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.ID" class="btn btn-sm bg-danger-light">
                            <i class="fas fa-times"></i> حـذف
                        </a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    